name: Wave Collapse CI

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Miniconda
      uses: w9jds/setup-miniconda@v2
      with:
        activate-environment: base
        environment-file: environment.yml

    - name: Install package
      run: |
        conda install pytest
        conda install pip
        pip install .
    - name: Test with pytest
      run: |
        pip install pytest-cov  # Install pytest-cov
        pytest --cov=./src/tests  # Run pytest with coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}



    